### ISSUE TITLE
Tracking issue for more examples

### ISSUE THREAD

**Issue by johnmave126** [johnmave126/tencent_scf#1]
I would like to add more examples to this repo:
* novel examples
  - [x] [biliplus-proxy](https://github.com/johnmave126/tencent_scf/tree/master/examples/biliplus-proxy), landed in db369132be9059d73a78d496cc039f3954010763
* official examples adapted from https://github.com/tencentyun/serverless-demo
  - [ ] hello world
  - [ ] [zip decompression](https://github.com/tencentyun/serverless-demo/tree/master/Python2.7-UnzipToCOS)
  - [ ] [heartbeat polling](https://github.com/tencentyun/serverless-demo/tree/master/Python2.7-PlayCheckByTimer)

  and more...

I also welcome contribution of examples.
