### ISSUE TITLE
Tracking issue for more built-in events/responses

### ISSUE THREAD

**Issue by johnmave126** [johnmave126/tencent_scf#2]
I would like to support all kinds of native triggers in Tencent Cloud

- [x] [Web API Gateway](https://cloud.tencent.com/document/product/583/12513): come with initial commit in [builtin/api.rs](https://github.com/johnmave126/tencent_scf/blob/master/src/builtin/api.rs)
- [ ] [websocket](https://cloud.tencent.com/document/product/583/32551)
- [ ] [COS trigger](https://cloud.tencent.com/document/product/583/9707)
- [ ] [CLS trigger](https://cloud.tencent.com/document/product/583/49587)
- [ ] [Timer trigger](https://cloud.tencent.com/document/product/583/9708)
- [ ] [CMQ Topic trigger](https://cloud.tencent.com/document/product/583/11517)
- [ ] [CKafka trigger](https://cloud.tencent.com/document/product/583/17530)
- [ ] [MPS trigger](https://cloud.tencent.com/document/product/583/50833)
- [ ] [CLB trigger](https://cloud.tencent.com/document/product/583/52635)

Most should be straightforward as we only need to deserialize the message as described in the documentation. Most don't have a response message. The already implemented Web API Gateway one might be the hardest one to implement.
